# Generated by Django 5.2.10 on 2026-01-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('roll_number', models.CharField(max_length=50, unique=True)),
                ('class_name', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=50)),
            ],
        ),
    ]
