# Generated by Django 5.2.10 on 2026-01-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_issuebook_delete_issuerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='issue_date',
            field=models.DateField(),
        ),
    ]
