# Generated by Django 5.2.10 on 2026-01-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_issuebook_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='status',
            field=models.CharField(choices=[('On Time', 'On Time'), ('Due Today', 'Due Today'), ('Late', 'Late')], default='On Time', max_length=20),
        ),
    ]
