# Generated by Django 5.2.10 on 2026-01-20 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_issuebook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
